"""Rename catalogue to catalog

Revision ID: 5b5a96375bc9
Revises: 8a5295fa3641
Create Date: 2021-02-15 17:34:36.597212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5a96375bc9'
down_revision = '8a5295fa3641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mutation_import_catalogue', table_name='mutation_import')
    op.alter_column('mutation_import', 'catalogue', new_column_name='catalog')
    op.create_index(op.f('ix_mutation_import_catalog'), 'mutation_import', ['catalog'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mutation_import_catalog', table_name='mutation_import')
    op.alter_column('mutation_import', 'catalog', new_column_name='catalogue')
    op.create_index(op.f('ix_mutation_import_catalogue'), 'mutation_import', ['catalogue'], unique=False)
    # ### end Alembic commands ###
